#pragma once
#include <Arduino.h>

#define DEVICE_NAME "Luz Dimerizavel"

#define DEVICE_TYPE_ON_OFF 1
#define DEVICE_TYPE_TEMPERATURE 2
#define DEVICE_TYPE_CONTACT 3
#define DEVICE_TYPE_OCCUPANCY 4
#define DEVICE_TYPE_DIMMABLE 5

#define DEVICE_TYPE DEVICE_TYPE_DIMMABLE

#define STATE_UPDATE_INTERVAL 5000
#define STATE_SEND_THRESHOLD 5
#define STATE_FORCE_INTERVAL 300000
#define TELEMETRY_INTERVAL 30000

#define DISCOVERY_PORT 5000
#define DISCOVERY_TIMEOUT 30000

#define BRIDGE_HOST "0.0.0.0"
#define BRIDGE_PORT 80

#define PWM_PIN 4
#define BUTTON_PIN 5
#define LED_PIN 2

#define PWM_FREQ 1000
#define PWM_RESOLUTION 10

#define LED_BLINK_WIFI_MS 200
#define LED_BLINK_BRIDGE_MS 2000